# Generated by Django 3.2.16 on 2022-11-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='l_t',
            field=models.DateTimeField(null=True, verbose_name='用户最后一次登录时间'),
        ),
    ]
